create extension if not exists pgcrypto;

create type work_order_status as enum ('draft','planned','scheduled','in_progress','blocked','complete','cancelled');
create type visit_status as enum ('planned','scheduled','travel','onsite','complete','cancelled');
create type cost_status as enum ('forecast','committed','actual','void');
create type employment_type as enum ('employee','contractor','partner');

create table regions (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, reporting_currency char(3) not null default 'USD');
create table service_teams (id uuid primary key default gen_random_uuid(), region_id uuid references regions(id), name text not null, manager_user_id uuid, unique(region_id,name));
create table technicians (id uuid primary key default gen_random_uuid(), employee_number text unique, first_name text not null, last_name text not null, email text, phone text, employment_type employment_type not null default 'employee', team_id uuid references service_teams(id), country_code char(2), home_city text, home_airport text, timezone text not null default 'UTC', latitude numeric(9,6), longitude numeric(9,6), hourly_cost numeric(12,2), overtime_multiplier numeric(5,2) default 1.5, currency char(3) default 'USD', utilization_target numeric(5,2) default 80.00, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table skills (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, category text);
create table technician_skills (technician_id uuid not null references technicians(id) on delete cascade, skill_id uuid not null references skills(id) on delete cascade, proficiency smallint not null check (proficiency between 1 and 5), verified_at date, primary key (technician_id,skill_id));
create table technician_time_off (id uuid primary key default gen_random_uuid(), technician_id uuid not null references technicians(id) on delete cascade, type text not null, starts_at timestamptz not null, ends_at timestamptz not null, status text not null default 'approved', check (ends_at > starts_at));

create table customers (id uuid primary key default gen_random_uuid(), name text not null, customer_number text unique, default_currency char(3));
create table sites (id uuid primary key default gen_random_uuid(), customer_id uuid references customers(id), region_id uuid references regions(id), site_code text not null unique, name text not null, country_code char(2), city text, address text, timezone text not null default 'UTC', latitude numeric(9,6), longitude numeric(9,6), reporting_currency char(3) not null default 'USD', created_at timestamptz not null default now());
create table assets (id uuid primary key default gen_random_uuid(), site_id uuid not null references sites(id) on delete cascade, asset_tag text not null, serial_number text, product_family text, model text, status text not null default 'active', commissioned_at date, unique(site_id,asset_tag));

create table service_requests (id uuid primary key default gen_random_uuid(), site_id uuid not null references sites(id), source text, external_reference text, priority smallint not null default 3, summary text not null, description text, requested_at timestamptz not null default now());
create table work_orders (id uuid primary key default gen_random_uuid(), work_order_number text not null unique, site_id uuid not null references sites(id), service_request_id uuid references service_requests(id), type text not null, status work_order_status not null default 'draft', priority smallint not null default 3, summary text not null, scope text, sla_due_at timestamptz, planned_start date, planned_end date, budget_amount numeric(14,2), budget_currency char(3), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table work_order_assets (work_order_id uuid not null references work_orders(id) on delete cascade, asset_id uuid not null references assets(id), primary key(work_order_id,asset_id));
create table service_visits (id uuid primary key default gen_random_uuid(), work_order_id uuid not null references work_orders(id) on delete cascade, visit_number smallint not null, status visit_status not null default 'planned', starts_at timestamptz, ends_at timestamptz, technicians_required smallint not null default 1, notes text, unique(work_order_id,visit_number), check (ends_at is null or starts_at is null or ends_at > starts_at));
create table technician_assignments (id uuid primary key default gen_random_uuid(), service_visit_id uuid not null references service_visits(id) on delete cascade, technician_id uuid not null references technicians(id), role text, assigned_at timestamptz not null default now(), unique(service_visit_id,technician_id));

create table cost_categories (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, parent_id uuid references cost_categories(id), is_active boolean not null default true);
insert into cost_categories(code,name) values ('LABOR','Labor'),('OVERTIME','Overtime'),('TRAVEL','Travel'),('AIRFARE','Airfare'),('HOTEL','Lodging'),('RENTAL_CAR','Rental Car'),('MILEAGE','Mileage'),('PER_DIEM','Per Diem'),('PARTS','Parts'),('FREIGHT','Freight'),('SUBCONTRACTOR','Subcontractor'),('EQUIPMENT_RENTAL','Equipment Rental'),('TOOLS','Tools'),('OTHER','Other') on conflict do nothing;
create table cost_entries (id uuid primary key default gen_random_uuid(), site_id uuid not null references sites(id), work_order_id uuid references work_orders(id), service_visit_id uuid references service_visits(id), technician_id uuid references technicians(id), category_id uuid not null references cost_categories(id), status cost_status not null, transaction_date date not null, description text not null, vendor_name text, quantity numeric(12,2) default 1, unit_cost numeric(14,4), amount numeric(14,2) not null, currency char(3) not null, fx_rate_to_reporting numeric(16,8) not null default 1, reporting_amount numeric(14,2) generated always as (round(amount * fx_rate_to_reporting,2)) stored, source_system text, source_reference text, created_at timestamptz not null default now(), check(amount>=0), check(fx_rate_to_reporting>0));
create table site_budgets (id uuid primary key default gen_random_uuid(), site_id uuid not null references sites(id) on delete cascade, fiscal_year int not null, category_id uuid references cost_categories(id), amount numeric(14,2) not null, currency char(3) not null, unique(site_id,fiscal_year,category_id));

create index idx_technicians_team on technicians(team_id) where is_active;
create index idx_work_orders_site_status on work_orders(site_id,status);
create index idx_visits_dates on service_visits(starts_at,ends_at);
create index idx_assignments_tech on technician_assignments(technician_id);
create index idx_cost_entries_site_date on cost_entries(site_id,transaction_date);
create index idx_cost_entries_category_status on cost_entries(category_id,status);

create view site_financial_summary as select s.id site_id,s.site_code,coalesce(sum(c.reporting_amount) filter(where c.status='actual'),0) actual_spend,coalesce(sum(c.reporting_amount) filter(where c.status='committed'),0) committed_spend,coalesce(sum(c.reporting_amount) filter(where c.status='forecast'),0) forecast_remaining,coalesce(sum(c.reporting_amount) filter(where c.status in ('actual','committed','forecast')),0) total_exposure from sites s left join cost_entries c on c.site_id=s.id and c.status<>'void' group by s.id,s.site_code;
